### ISSUE TITLE
[BUG]? Stop Actor Sound

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-sound-enhancements#13]
Clicking the `Stop` button on a token only stops the sound locally, not for all players.
![image](https://user-images.githubusercontent.com/99844555/226489375-1e4baa63-1ab4-46ce-9c82-519b3cf87f45.png)

Sound Enhancements 10.1

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
