### ISSUE TITLE
Compatibility with SyrinControl

### ISSUE THREAD

**Issue by notrealdan** [ironmonk88/monks-sound-enhancements#14]
**Is your feature request related to a problem? Please describe.**
Monk's Sound Enhancements conflicts a bit with recent versions of the SyrinControl module.  Both modules make changes to the Edit Playlists dialog box.  I believe the issues are just cosmetic.

**Describe the solution you'd like**
SyrinControl creates its own playlists, and I don't think those playlists benefit from Monk's Sound Enhancements anyways, since they're not native Foundry sounds anyways.  SyrinControl playlists have an extra flag set: `flags.syrinscape`
Could your module simply ignore playlists that have that flag?  Or some better solution you can think of would be fine.

**Additional context**
See an open issue over on the SyrinControl github, here:
https://github.com/frondeus/fvtt-syrin-control/issues/95

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
