### ISSUE TITLE
[BUG] Item Sounds not playing when using items, but everything else is working fine?

### ISSUE THREAD

**Issue by amsando5** [ironmonk88/monks-sound-enhancements#19]
I'm currently unable to get the item sounds to run at all when rolling/ activating an item, and I'm really not sure if I'm doing something wrong here. I can hit the "play" button in the sound preview window to test the sound and it works there no problem, and attaching sound effects to NPCs works without a hitch, but no sounds play on items when rolling them/ doing anything else with them.

I assumed it was a mod incompatibility, but I've tested the mod by itself with nothing else enabled and the error still replicates. Is there some incompatibility I'm not aware of, or is there some aspect/ setting of FoundryVTT I should be changing?

**Foundry Details:**
FoundryVTT Version: v10.291
DnD5e - Fifth Edition System: v2.2.2
Mod Version: 10.03 (was 10.01, but manually replaced mod files to update since v11 version won't let me auto update in Modules List)

**Comment by patrickburk1988** [comment]
Doesn't appear to be working with version 11, either (at least in the Delta Green system).

**Comment by ironmonk88** [comment]
v10 versions are no longer supported or updated.
This seems to be working in v11, although limited to systems that support it.  Which currently means only D&D5e and PF2e are reliable.
