### ISSUE TITLE
[BUG] Drag & Drop on Sounds Tab

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-sound-enhancements#20]
https://github.com/ironmonk88/monks-sound-enhancements/assets/99844555/cfa20126-8a00-48c8-95e4-f3005b00ff8a

(I know the playlist names are the same, but they are two different ones).

Foundry 11.306
Sound Enhancements 11.03

**Comment by ironmonk88** [comment]
Fixed in the latest version
