### ISSUE TITLE
[Feature Request] Allow drag & drop (move, but not copy) between the Sound tabs of two playlists.

### ISSUE THREAD

**Issue by Nedrapter** [ironmonk88/monks-sound-enhancements#21]
**Is your feature request related to a problem? Please describe.**
Currently there's no other module for v11 that helps you organize/re-order your tracks easily. The core method is way too slow. 
**Describe the solution you'd like**
Include a tickbox in the module's settings, whether the drag behavior should be a copy or a move functionality.

**Additional context**
With the functionality of the Sounds tab on each playlist and the ability to drag (move, not copy), from one playlist to another, the re-organization of playlists becomes so much more comfortable, as the vertical structure of the sidebar is not comfortable to scroll up and down when you have lots of items there.

**Comment by ironmonk88** [comment]
Fixed in the latest version
