### ISSUE TITLE
[BUG] Actor Sounds Only Play for First Combat Round

### ISSUE THREAD

**Issue by Armandeus66** [ironmonk88/monks-sound-enhancements#26]
**Describe the bug**
1. Playing the set sound for a token on their turn stops working for players after the first round of combat (PF2E). The GM can still hear it.
2. Playing the actor sound from the actor sheet is also not heard by players at this point.

**To Reproduce**
1. Assign a sound to an actor.
3. Assign a token and place on scene and in the combat tracker.
4. Advance to round 2.
5. Actor sounds are no longer played for PCs and NPCs when their turn comes. (They are played for the GM only.)

**Expected behavior**
The sound should play at the start of the actor's turn every round.

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version 11.315
 - Pathfinder 2e 5.11.5
 - Module version 11.05

**Comment by ironmonk88** [comment]
Fixed in the latest version
