### ISSUE TITLE
[BUG] Actor Sound 5e

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-sound-enhancements#27]
The actor sound button doesn't show up on the new 5e sheets.

![image](https://github.com/ironmonk88/monks-sound-enhancements/assets/99844555/74277cce-bc0e-4d28-86a6-319de5f2544f)

Foundry 11.315
SE 11.06
D&D 5e 3.0.0

**Comment by ironmonk88** [comment]
Fixed in the latest version
