### ISSUE TITLE
[Feature Request] New Tidy 5e Sheets Compatibility

### ISSUE THREAD

**Issue by kgar** [ironmonk88/monks-sound-enhancements#28]
The Sound Effects button is missing from the new [Tidy 5e Sheets](<https://github.com/kgar/foundry-vtt-tidy-5e-sheets/>).
This is a feature request to establish compatibility between our modules.

![image](https://github.com/ironmonk88/monks-sound-enhancements/assets/4632129/e683ffe1-94e6-4a13-bf13-f5ff1842f173)

**Additional context**
Tidy 5e Sheets is a full rewrite of the original module. It runs on the svelte web framework and doesn't trigger the full render hook as often. Also, the HTML structure is subject to change, so I provide my own specific tags and attributes for targeting things. For these reasons, I have provided [an API](<https://kgar.github.io/foundry-vtt-tidy-5e-sheets/classes/Tidy5eSheetsApi.html>) for a variety of tasks, including [registering Actor content](<https://kgar.github.io/foundry-vtt-tidy-5e-sheets/classes/Tidy5eSheetsApi.html#registerActorContent>).

Tidy's API sits cleanly behind a hook, so it does not disturb the regular flow of things and will be silently ignored if the module is turned off. Here is an example of registering sound effect button:

```js
Hooks.once('tidy5e-sheet.ready', (api) => {
  api.registerActorContent(
    new api.models.HtmlContent({
      html: (data) => {
        let soundEffect = getProperty(
          data.actor,
          'flags.monks-sound-enhancements.sound-effect'
        );
        if (!soundEffect) {
          soundEffect = getProperty(
            data.actor,
            'flags.monks-little-details.sound-effect'
          );
          if (soundEffect)
            data.actor.setFlag(
              'monks-sound-enhancements',
              'sound-effect',
              soundEffect
            );
        }

        let hasSound = soundEffect != undefined;

        let button = $('<button>')
          .attr('type', 'button')
          .attr('id', 'mseCharacterSound')
          .toggleClass('loaded', hasSound)
          .html('<i class="fas fa-volume-up"></i>');

        return button.get(0).outerHTML;
      },
      injectParams: {
        selector: `[data-tidy-sheet-part="name-container"]`,
        position: 'beforebegin',
      },
      enabled: (params) =>
        setting('actor-sounds') !== 'none' &&
        (setting('actor-sounds') !== 'npc' || params.actor.type === 'npc'),
      onRender: (params) => {
        params.element
          .querySelector('#mseCharacterSound')
          .addEventListener('click', () =>
            ActorSounds.showDialog.bind(app, 'actor')
          );
      },
    })
  );
});
```

**Comment by kgar** [comment]
Any thoughts on this?

**Comment by ironmonk88** [comment]
Fixed in the latest version
