### ISSUE TITLE
Prevent players from adjusting current sound volume

### ISSUE THREAD

**Issue by CarlosFdez** [ironmonk88/monks-sound-enhancements#3]
There seems to be general confusion between global sound volumes and currently playing sound volume, with people believing global volumes affect everyone and current playing volume is local only (when its actually backwards). This causes players to mess up the audio balance of things no matter how much I as the GM attempt to curate it. It'd be nice to hide or disable the volume slider on the currently playing tracks for players, and perhaps have global volume controls open by default (or always open), as a way to guide users towards the global volume controls rather than adjusting only the current song.

If it can't or shouldn't be done here, I wouldn't mind making a temporary module for it, but figured I should ask first!

**Comment by CarlosFdez** [comment]
Its been a while so I'll make a module for this. Thank you though.

**Comment by ironmonk88** [comment]
Yeah, v10 changes are taking a long time.
Checked into this briefly but the issue seems to have been fixed in v10.  And since Sound Enhancement is v10 only, there's nothing much I could do about it.

**Comment by CarlosFdez** [comment]
Ah, its not a bug, it was a feature request. Players tend to get confused between global sound volume and current playing audio, changing the current playing volume instead of the global volumes and doing so for each song.

What I did locally was force the global volume controls to stay open and disable the slider for the currently playing audio if the current user is a player:

![image](https://user-images.githubusercontent.com/1286721/192941738-b53b9cea-b79b-41ec-b993-653ac9cfd119.png)

I'm tempted on also relabeling global volume controls to make it obvious that those are client settings, but that would be annoying to localize.
