### ISSUE TITLE
Monks Sound Effects API

### ISSUE THREAD

**Issue by FoundryGM** [ironmonk88/monks-sound-enhancements#31]
So, there is no documentation on how to utilize this module w macros so I am opening a ticket to ask my question: is there a way to use the modules api to add a sound effect to a token/actor, and if so, how would that be done? I have a ton of sound files I want to apply to my actors in bulk which is why I ask.

**Comment by ironmonk88** [comment]
`actor.addSound(audiofile, volume)`

actor = and Actor object
audiofile = the file path for the audio file
volume = to volume between 0 and 1
