### ISSUE TITLE
[BUG]? Drag Sound to Compendium Playlist

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-sound-enhancements#33]
Not sure if this was ever a feature; wiki only has mentions it working in the reverse (which works fine), but dragging a sound from an in-world playlist to a compendium playlist fails & errors.

https://github.com/ironmonk88/monks-sound-enhancements/assets/99844555/e41f6812-dac8-4efe-9367-59b67b2701b1

Foundry 12.327
Sound Enhancements 12.01

**Comment by ironmonk88** [comment]
Fixed in the latest version
