### ISSUE TITLE
In foundry v11 I had no problems with Monks-sound, but in v12 I can't save the sounds in the tokens.

### ISSUE THREAD

**Issue by DarthBalrog** [ironmonk88/monks-sound-enhancements#36]
**Describe the bug**
Hi,
I upgraded from foundry v.11 to foundry v12.
In v11 I had no problems with Monks-sound, but in v12 I can't save the sounds in the tokens.
After select the sound.ogg I click "save" but it didn't save them.
Why?
Could you help me solve this problem?
Thanks!

**To Reproduce**
I follow the same steps as in v.11.
At the end, when I click save, it doesn't.

**Expected behavior**
I'd like it save the sound as in version 11. (:

**Screenshots**
I add a screenshot.
![Monks-sound01](https://github.com/user-attachments/assets/237da98f-59e0-4f92-9dcb-547197b51d75)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version v12
 - System D&D5e v3
 - Module version 12.02
 - Are there any errors in the console:
 **foundry.js:6668 TypeError: this.object.addSound is not a function
    at ActorSoundDialog._updateObject (actor-sounds.js:364:21)
    at ActorSoundDialog._onSubmit (foundry.js:6665:18)
    at HTMLButtonElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)**
 
 
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.
Yes, see the second pic.
![Monks-sound02](https://github.com/user-attachments/assets/806e6ae0-af33-4cfa-a42a-90e1486782b7)

**Additional context**
Thanks for any help.

**Comment by turthalion** [comment]
Confirmed that I've seen this on my Foundry too. Can't save actor sounds, whether opening from the scene or in the sidebar.

I select a sound, click Save, nothing happens, the "Actor Sound" dialog won't close when hitting Save.

**Console error:**
**foundry.js:6668 TypeError: this.object.addSound is not a function
    at ActorSoundDialog._updateObject (actor-sounds.js:364:21)
    at ActorSoundDialog._onSubmit (foundry.js:6665:18)
    at HTMLButtonElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)**
    
**Browser:** Brave 1.73.104 (Chromium 131.0.6778.204)
**Foundry:** V12 Build 331 running on Ubuntu 22.04, node.js 20
**System:** PF2e 6.8.0
**Module version:** 12.02

**Comment by turthalion** [comment]
After retesting with 12.03, I can confirm this issue NO LONGER OCCURS for me with 12.03. Thanks so much for the quick work.

**Comment by DarthBalrog** [comment]
> After retesting with 12.03, I can confirm this issue NO LONGER OCCURS for me with 12.03. Thanks so much for the quick work.

Yes, I confirm. With 12.03 it works. Thank you.
