### ISSUE TITLE
Color Changing

### ISSUE THREAD

**Issue by peterprokurist** [ironmonk88/monks-sound-enhancements#5]
Is there a way to change the colors or the contrasts of the displayed playlists?
In the colors of my game system (DSA/TDA), the names of the playlists are displayed in black on a violet background and the controls are light gray on beige.

![image](https://user-images.githubusercontent.com/115837717/196234720-c7b4e17b-fd25-48ed-b5da-587dfae78d55.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
