### ISSUE TITLE
[BUG] Actor Sounds

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-sound-enhancements#8]
Actor sounds don't seem to fall under any of the volume sliders. Also, there doesn't seem to be any way to stop a sound once its being played.
![image](https://user-images.githubusercontent.com/99844555/211125587-d5742f86-6af6-4fa3-809b-9206fd82088c.png)

MSE 10.1

**Comment by ironmonk88** [comment]
Added the sound effects volume slider to the latest release
